Asdf to mise (#1)

diff --git a/envmgr b/envmgr
--- a/envmgr
+++ b/envmgr
@@ -4,41 +4,42 @@
 # Also upgrades, cleanups homebrew and similar stuff in single command
 # Actually absurdly ugly, but hey, it works! Somehow.
 
-#colors
+# colors
 COLOR_RESET="$(tput sgr0)"
 COLOR_GREEN="$(tput setaf 2)"
 
-#source config
-source ~/.rc/envmgr.conf
+# source config
+# shellcheck disable=SC1091
+source "${HOME}/.rc/envmgr.conf"
 
 # Function to symlink dotfiles
 # Checking if OS is Linux (GNU coreutils), if not, we assume OS uses BSD utils
 symlink() {
-  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    ln -sfvn ${1} ${2}
+  if [[ "${OSTYPE}" == "linux-gnu"* ]]; then
+    ln -sfvn "${1}" "${2}"
   else
-    ln -sfvh ${1} ${2}
+    ln -sfvh "${1}" "${2}"
   fi
 }
 
-#Symlink dotfiles and envmgr from ~/.rc to ~
+# Symlink dotfiles and envmgr from ${HOME}/.rc to ~
 install_env() {
   echo -e "${COLOR_GREEN}Deploying environment${COLOR_RESET}"
-  cd ~/.rc || exit
-  echo -e "${COLOR_GREEN}Deploying dotfiles from $(pwd) to ${HOME}${COLOR_RESET}"
-  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+  cd "${HOME}/.rc" || exit
+  echo -e "${COLOR_GREEN}Deploying dotfiles from $(pwd || true) to ${HOME}${COLOR_RESET}"
+  if [[ "${OSTYPE}" == "linux-gnu"* ]]; then
     dotdirs=( .config .local/share )
     for dir in "${dotdirs[@]}"; do
-      if [[ ! -d ~/${dir} ]]; then
-        mkdir -p ~/${dir}
+      if [[ ! -d ${HOME}/${dir} ]]; then
+        mkdir -p "${HOME}/${dir}"
       fi
     done
     dotfiles=("${dotfiles[@]}" "${linuxenv[@]}")
   fi
   for file in "${dotfiles[@]}"; do
-    symlink ~/.rc/.${file} ~/.${file}
+    symlink "${HOME}/.rc/.${file}" "${HOME}/.${file}"
   done
-  symlink ~/.rc/envmgr ~/.rc/.bin/envmgr
+  symlink "${HOME}/.rc/envmgr" "${HOME}/.rc/.bin/envmgr"
   cd - >&/dev/null || exit 1
   echo -e "${COLOR_GREEN}Finished deploying dotfiles${COLOR_RESET}"
   echo -e "${COLOR_GREEN}Installing vim plugins${COLOR_RESET}"
@@ -46,75 +47,86 @@ install_env() {
   echo -e "${COLOR_GREEN}Finished installing vim plugins${COLOR_RESET}"
 }
 
-# Install asdf and plugins (ruby, python, nodejs, golang)
-# Plugins listed in envmgr.conf in asdf_plugins array
-# TODO: add cleanup of old versions, maybe as separate func
+# Install mise and tools (python, node, ruby, golang)
+# TODO: detect last version automatically
+# TODO: verify downloaded binary against shasum
 install_devenv() {
-  #install asdf
-  echo -e "${COLOR_GREEN}Installing asdf${COLOR_RESET}"
-  if [[ ! -d "$HOME/.asdf" ]]; then
-    git clone https://github.com/asdf-vm/asdf.git ~/.asdf
+  # install mise
+  echo -e "${COLOR_GREEN}Installing mise${COLOR_RESET}"
+  # detect if it's already installed, if yes, just do self-update
+  if [[ -f ${HOME}/.local/bin/mise ]]; then
+    mise self-update
   else
-    cd ~/.asdf && git pull
+    # if not, download
+    # detect os
+    case ${OSTYPE} in
+        "linux-gnu"*) mise_system="linux" ;;
+        "darwin"*) mise_system="macos" ;;
+        *) echo "Unable to detect supported operating system" || die ;;
+    esac
+    # detect arch since naming is non-standard
+    case $(uname -m) in
+        "x86_64"*) mise_architecture="x64" ;;
+        "arm64"*) mise_architecture="arm64" ;;
+        *) echo "Unable to detect supported architecture" || die ;;
+    esac
+    # if we have jq available, parse latest version, otherwise use one from configs
+    if hash jq 2>/dev/null; then
+      mise_version=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jdx/mise/releases | jq -r '.[0].tag_name')
+    fi
+    mise_download_url=https://github.com/jdx/mise/releases/download/"${mise_version}"/mise-"${mise_version}"-"${mise_system}"-"${mise_architecture}"
+    echo -e "${COLOR_GREEN}Downloading mise from ${mise_download_url}${COLOR_RESET}"
+    curl -L "${mise_download_url}" > "${HOME}/.local/bin/mise"
+    chmod +x "${HOME}/.local/bin/mise"
+    # init mise, force bash because that's what we default
+    eval "$("${HOME}"/.local/bin/mise activate bash || true)"
   fi
-  #init asdf
-  source ~/.rc/sh.d/S01_env
-  #install plugins
-  echo -e "${COLOR_GREEN}Installing asdf plugins${COLOR_RESET}"
-  for lang in "${asdf_plugins[@]}"; do
-    asdf plugin-add ${lang}
-  done
-  #setup default packages
+  # setup default packages
   for gem in "${gems[@]}"; do
-    grep -sq ${gem} ~/.default-gems || echo ${gem} >> ~/.default-gems
+    grep -sq "${gem}" "${HOME}/.default-gems" || echo "${gem}" >> "${HOME}/.default-gems"
   done
   for egg in "${eggs[@]}"; do
-    grep -sq ${egg} ~/.default-python-packages || echo ${egg} >> ~/.default-python-packages
+    grep -sq "${egg}" "${HOME}/.default-python-packages" || echo "${egg}" >> "${HOME}/.default-python-packages"
   done
   for npm_package in "${npms[@]}"; do
-    grep -sq ${npm_package} ~/.default-npm-packages || echo ${npm_package} >> ~/.default-npm-packages
+    grep -sq "${npm_package}" "${HOME}/.default-npm-packages" || echo "${npm_package}" >> "${HOME}/.default-npm-packages"
   done
   for go_pkg in "${gopkgs[@]}"; do
-    grep -sq ${go_pkg} ~/.default-golang-pkgs || echo ${go_pkg} >> ~/.default-golang-pkgs
+    grep -sq "${go_pkg}" "${HOME}/.default-golang-pkgs" || echo "${go_pkg}" >> "${HOME}/.default-golang-pkgs"
   done
-  #install latest versions of langs
-  #nodejs verifies signatures, assuming trusted environment
-  #FIXME: support GPG verification for nodejs and python
-  echo -e "${COLOR_GREEN}Installing languages with asdf${COLOR_RESET}"
-  for lang in "${asdf_plugins[@]}"; do
-    latest_version=$(asdf list-all ${lang} | sort -V | grep -v '[a-z]' | tail -1)
-    echo "Latest ${lang} => ${latest_version}"
-    NODEJS_CHECK_SIGNATURES=no asdf install ${lang} ${latest_version}
-    asdf global ${lang} ${latest_version}
+  # install default tools
+  echo -e "${COLOR_GREEN}Installing default tools${COLOR_RESET}"
+  for mise_tool in "${mise_tools[@]}"; do
+    mise install "${mise_tool}"
+    mise use "${mise_tool}"
   done
-  echo -e "${COLOR_GREEN}Finished installing asdf${COLOR_RESET}"
+  echo -e "${COLOR_GREEN}Finished installing mise${COLOR_RESET}"
 }
 
-#Installs homebrew on os x (global, script) and linux (manual, homedir)
-#Also installs apps from ~/.rc/Brewfile
+# Installs homebrew on os x (global, script) and linux (manual, homedir)
+# Also installs apps from ${HOME}/.rc/Brewfile
 install_homebrew() {
-  cd ~/.rc || exit
+  cd "${HOME}/.rc" || exit
   echo -e "${COLOR_GREEN}Installing homebrew and favourite packages${COLOR_RESET}"
   if hash brew 2>/dev/null; then
     echo "Brew is already installed!"
     else
-      if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-        git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
-        mkdir ~/.linuxbrew/bin
-        ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
-        eval $(~/.linuxbrew/bin/brew shellenv)
-      elif [[ "$OSTYPE" == "darwin"* ]]; then
-        #probably i should migrate to manual install.
-        #Running (even respected) scripts from interwebs is stupid.
-        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-        eval "$(/opt/homebrew/bin/brew shellenv)"
+      if [[ "${OSTYPE}" == "linux-gnu"* ]]; then
+        git clone https://github.com/Homebrew/brew "${HOME}/.linuxbrew/Homebrew"
+        mkdir "${HOME}/.linuxbrew/bin"
+        ln -s "${HOME}/.linuxbrew/Homebrew/bin/brew" "${HOME}/.linuxbrew/bin"
+        eval "$("${HOME}"/.linuxbrew/bin/brew shellenv || true)"
+      elif [[ "${OSTYPE}" == "darwin"* ]]; then
+        # TODO: Migrate to manual install
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh || true)"
+        eval "$(/opt/homebrew/bin/brew shellenv || true)"
       fi
   fi
   brew bundle
 }
 
 install_kubectl_plugins() {
-  cd ~/.rc || exit
+  cd "${HOME}/.rc" || exit
   echo -e "${COLOR_GREEN}Installing kubectl plugins${COLOR_RESET}"
   if hash kubectl-krew 2>/dev/null; then
     kubectl krew install "${kubectl_plugins}"
@@ -122,50 +134,54 @@ install_kubectl_plugins() {
 }
 
 install_helm_plugins() {
-  cd ~/.rc || exit
+  cd "${HOME}/.rc" || exit
   echo -e "${COLOR_GREEN}Installing helm plugins${COLOR_RESET}"
   if hash helm 2>/dev/null; then
     helm plugin install "${helm_plugins}"
   fi
 }
 
-#Nukes whole dotfiles setup
-#TODO: Maybe use shred instead of rm?
+# Nukes whole dotfiles setup
+# TODO: Maybe use shred instead of rm?
 env_nuke() {
   echo "Cleaning up env"
   echo "Removing dotfiles symlinks"
   for file in "${dotfiles[@]}"; do
-    rm -vf ~/.${file}
+    rm -vf "${HOME}/.${file}"
   done
   echo "Cleaning up devenv"
-  rm -rvf ~/.asdf
+  #for backwards compatibility
+  rm -rvf "${HOME}/.asdf"
+  rm -rvf "${HOME}/.local/bin/mise"
+  rm -rvf "${HOME}/.local/share/mise"
+  rm -rvf "${HOME}/.local/state/mise"
   echo "Removing history"
-  rm -vf ~/.zsh-history
-  rm -vf ~/.bash_history
+  rm -vf "${HOME}/.zsh-history"
+  rm -vf "${HOME}/.bash_history"
   echo "Removing linuxbrew"
-  rm -rf ~/.linuxbrew
+  rm -rf "${HOME}/.linuxbrew"
   echo "Removing dotfiles directory"
-  rm -rf ~/.rc
+  rm -rf "${HOME}/.rc"
 }
 
-#Checks for updates in env, homebrew, vim plugins and mac app store
+# Checks for updates in env, homebrew, vim plugins and mac app store
 env_housekeeper() {
   echo -e "${COLOR_GREEN}Started housekeeping${COLOR_RESET}"
   echo -e "${COLOR_GREEN}Updating dotfiles repo${COLOR_RESET}"
-  git -C ~/.rc pull
+  git -C "${HOME}/.rc" pull
   echo -e "${COLOR_GREEN}Cleaning up outdated symlinks${COLOR_RESET}"
-  find -L $HOME -maxdepth 1 -type l -exec rm -i {} +
+  find -L "${HOME}" -maxdepth 1 -type l -exec rm -i {} +
   if hash brew 2>/dev/null; then
     echo -e "${COLOR_GREEN}Updating and cleaning up homebrew${COLOR_RESET}"
     brew update
     brew upgrade
     brew cleanup
   fi
-  # Update asdf
-  echo -e "${COLOR_GREEN}Updating asdf and asdf plugins${COLOR_RESET}"
-  if hash asdf 2>/dev/null; then
-    asdf update
-    asdf plugin-update --all
+  # Update mise
+  echo -e "${COLOR_GREEN}Updating mise and mise plugins${COLOR_RESET}"
+  if hash mise 2>/dev/null; then
+    mise self-update
+    mise upgrade --bump
   fi
   if hash kubectl-krew 2>/dev/null; then
     kubectl krew upgrade
@@ -188,7 +204,7 @@ env_housekeeper() {
   echo -e "${COLOR_GREEN}Housekeeping finished${COLOR_RESET}"
 }
 
-#Arguments parsing
+# Arguments parsing
 case "${1}" in
   env) install_env ;;
   devenv) install_devenv ;;
@@ -199,7 +215,7 @@ case "${1}" in
   *)
     echo "Command list:"
     echo "env - symlink dotfiles"
-    echo "devenv - install asdf with plugins"
+    echo "devenv - install mise with plugins"
     echo "brew - install homebrew and packages from bundle"
     echo "fullenv - env, devenv and brew combined"
     echo "nuke - remove (almost) everything installed by envmgr"
